import Head from 'next/head';
import HomeLayout from '@/components/HomeLayout';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { MovieListType } from '@/types/MovieList';
import { GetServerSideProps } from 'next';

interface Props {
  movieResults: MovieListType[];
}

export default function Home({ movieResults }: Props) {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!session) {
      router.push({
        pathname: '/login',
      });
    }
    return () => {};
  }, []);

  if (status === 'loading') return <p>Loading...</p>;

  // @ts-ignore
  return (
    <>
      <Head>
        <title>Disney Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeLayout movieResults={movieResults} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const movieResults = await fetch(
    'https://movies-api-wine.vercel.app/api/movie'
  ).then((res) => res.json());

  return {
    props: {
      movieResults,
    },
  };
};
