import Head from 'next/head';
import HomeLayout from '@/components/HomeLayout';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!session) {
      router.push({
        pathname: '/login',
      });
    }
    return () => {};
  }, []);

  if (status === 'loading') return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Disney Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeLayout />
    </>
  );
}
